name: Snapshot entire Webflow site

# 👇 allow the workflow to push back to the repo
permissions:
  contents: write

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # needed when pushing

      - name: Install wget
        run: sudo apt-get update && sudo apt-get install -y wget

      - name: Prepare folder
        run: |
          rm -rf snapshots/latest
          mkdir -p snapshots/latest

      - name: Mirror full site
        run: |
          wget \
            --mirror \
            --convert-links \
            --adjust-extension \
            --page-requisites \
            --no-parent \
            --wait=0.5 --random-wait \
            --no-check-certificate \
            -P snapshots/latest \
            https://studioprimal02.webflow.io/

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Auto full-site snapshot $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes."
          fi
