name: Snapshot all pages (HTML + CSS, no images)

permissions:
  contents: write         # allow the workflow to commit back to the repo

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes (change if you like)
  workflow_dispatch:          # manual "Run workflow" button

jobs:
  snapshot:
    runs-on: ubuntu-latest
    env:
      SITE: https://studioprimal02.webflow.io    # <-- your staging domain
      # Webflow asset/CDN hosts that serve CSS/JS
      ASSET_DOMAINS: studioprimal02.webflow.io,assets.website-files.com,uploads-ssl.webflow.com,cdn.prod.website-files.com
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y wget curl

      - name: Prepare folder
        run: |
          rm -rf snapshots/latest
          mkdir -p snapshots/latest

      - name: Fetch sitemap and extract URLs
        run: |
          set -e
          curl -fsSL "$SITE/sitemap.xml" -o snapshots/latest/sitemap.xml
          # extract <loc> values
          grep -oP '(?<=<loc>).*?(?=</loc>)' snapshots/latest/sitemap.xml > snapshots/latest/urls.txt
          echo "Found $(wc -l < snapshots/latest/urls.txt) URLs"

      - name: Download each page (HTML + CSS only)
        run: |
          while IFS= read -r URL || [ -n "$URL" ]; do
            [ -z "$URL" ] && continue
            SAFE=$(echo "$URL" | sed -E 's~https?://~~' | sed 's~/~_~g')
            OUTDIR="snapshots/latest/$SAFE"
            mkdir -p "$OUTDIR"
            echo ">> Fetching $URL"
            wget -q \
              --page-requisites \                 # grab assets referenced by the page
              --adjust-extension \                 # save .html when needed
              --convert-links \                    # make links local
              --span-hosts \                       # allow CDN hosts
              --domains="${ASSET_DOMAINS}" \       # whitelist (prevents wandering)
              --reject=gif,jpg,jpeg,png,webp,avif,svg,ico,bmp,tiff,mp4,webm \  # skip images/video
              --no-check-certificate \
              --wait=0.5 --random-wait \
              -P "$OUTDIR" "$URL" || echo "WARN: wget failed for $URL"
          done < snapshots/latest/urls.txt

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Snapshot (HTML+CSS) from sitemap $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes."
          fi
